### ISSUE TITLE
The "Home" breadcrumb link doesn't act as user would expect

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/microsetta-interface#33]
The "Home" breadcrumb link doesn't ever take a user back to the home page--the one where they see the cool "How It Works" graphic and are asked to sign up or log in.   Behind the scenes, the link DOES send the user to the "/home" endpoint again, but the server processing for that endpoint determines what state the user is in (either needs to set up account details or is ready to set up/work with sources) and sends them right back to either the account set up or the account details page :-| 

I suggest we remove "Home" from the breadcrumb trail ... I don't think it adds anything except confusion. @specsdom , thoughts?

**Comment by specsdom** [comment]
I think it should be okay right now to remove it from the breadcrumb trail entirely.  There does need to be a way to return to the home portal though (or depending on the state of the user, to the necessary page). One option is to link the Microsetta/UCSD logo to "/home".

This also ties in with a long run goal, where ideally the breadcrumb nav would be completely removed. I didn't want to completely remove it yet though until all the new changes have gone in, since they account for navigation between pages.

**Comment by wasade** [comment]
Closing as reported as fixed
